service: stared-awesome-creator

package:
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: prod
  memorySize: 512
  timeout: 900
  logRetentionInDays: 14
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/awesome_list_stars"

functions:
  star-manager:
    handler: bin/app
    reservedConcurrency: 1
    events:
      - schedule: rate(day)